### PR TITLE
Ensure hand has no duplicate cards for standard game

### LINKED ISSUE #14: isPossible === true with duplicate cards
Hi, I'm poking around with the library and making a few tests before using it. If I solve a handle with two duplicate cards (Queen of diamond for example) the returning structure still has a `isPossible` flag to true. Shouldn't it be false?

### PR DESCRIPTION
**Pull request by fvilers**
Fixes #14.

### CODE REVIEW

**Comment by goldfire** [comment]
Thanks! I'm going out of town, but I'll look this over when I get back next week.

**Comment by fvilers** [comment]
Any news?

**Comment by fvilers** [comment]
Are you back in town?

**Comment by ericblade** [comment]
@goldfire ? :-)

**Comment by RomeroCarranzaEmiliano** [comment]
goldfire is still alive?

@fvilers 
@ericblade

**Comment by fvilers** [comment]
I don't know...

**Comment by RomeroCarranzaEmiliano** [comment]
@fvilers what do we do if he doesn't appear? This module is quite cool. Is there a possibility to clone it or something?

**Comment by fvilers** [comment]
I'm not the owner, I was just submitting a PR. Feel free to fork and maintain ;-)

**Comment by RomeroCarranzaEmiliano** [comment]
there I forked it... [here](https://github.com/RomeroCarranzaEmiliano/pokersolver)

**Comment by fvilers** [comment]
@goldfire Bump ! :-)

**Comment by goldfire** [comment]
Sorry, I didn't realize I never came back to this. Thanks for the bump! I've just released this to npm in v2.1.4.

**Pull request merged**
